zoo:
  cages: 10
  animals:
    liens:
      quantity: 4
      quantity_in_cage: 3
    crocodiles:
      quantity: 4
      quantity_in_cage: 2
    elephants:
      quantity: 3
      quantity_in_cage: 2
