easy_admin:
    site_name: 'Admin panel'
    list:
        max_results: 20
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'


#Подключение в одном файле 
# design:
#         menu:
#           - label: 'Blog'
#             icon: 'newspaper-o'
#             children:
#                 - {entity: 'Post', icon: 'newspaper-o', label: 'Posts'}
#                 - {entity: 'Category', icon: 'inbox', label: 'Categories'}
#     entities:
#       Category:
#         class: App\Domain\Blog\Entity\Category
#         form:
#             fields:
#                 - {property: 'name'}
#                 - {property: 'slug'}
#       Post:
#         class: App\Domain\Blog\Entity\Post



# Очень простое подключение
      # entities:
#        # List the entity class name you want to manage
#        - App\Domain\Blog\Entity\Product
      #  - App\Domain\Blog\Entity\Post
#        - App\Domain\Blog\Entity\User