easy_admin:
    entities:
      Category:
        class: App\Entity\Category
        form:
            fields:
                - {property: 'name'}
                - {property: 'slug'}
        list:
          actions:
            - {name: 'edit', icon: 'pencil', lable: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', lable: false, css_class: 'btn btn-danger'}