easy_admin:
  entities:
    PostImage:
      class: App\Entity\Image
      form:
        fields:
          - 'name'
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'posts', label: 'Post' }
      list:
        fields:
          - 'id'
          - 'name'
          - { property: 'image',  type: 'image', base_path: '%app.path.post_images%' }
          - { property: 'postname',  label: 'Post' }
        actions:
          - {name: 'edit', icon: 'pencil', lable: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', lable: false, css_class: 'btn btn-danger'}
      search:
        fields: ['name', 'posts.name']